name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ['prod', 'dr']
    steps:
    - name: Set env
      run: |
        echo "${{matrix.env}}_value"
        echo "${{matrix.env}}_value='True'"
        echo "${{matrix.env}}_value='True'" >> $GITHUB_ENV
    - name: Test
      run: |
        sleep 10
        echo ${{ env.prod_value }}
        echo ${{ env.dr_value }}
        echo ${{matrix.env}}_value


        
